version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@maven
        name: build_maven
        displayName: Maven 构建
        jdkVersion: 8
        mavenVersion: 3.3.9
        commands:
          - curl -O https://bazel.build/bazel-release.pub.gpg
          - apt-key add bazel-release.pub.gp
          - gpg --list-keys
          - cat <(echo -e "${OSSRH_GPG_SECRET_KEY}") | gpg --batch --import
          - gpg --list-secret-keys --keyid-format LONG
          - mvn --batch-mode -Dgpg.passphrase=${gpg_passphrase} clean deploy
        settings:
          - certificate: af4838f0-5c64-013c-9226-626c6c53c0ec
            isRelease: true
            isSnapshot: false
        caches:
          - ~/.m2
        strategy: {}
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        strategy: {}
        dependsOn: build_maven
  - name: release
    displayName: 发布
    strategy: naturally
    trigger: auto
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        strategy: {}
